software_bootstrap:
    - hosts: all
      command: touch xyz.txt
    - hosts: power_servers[0]
      command: |
        set -e
        wget https://raw.githubusercontent.com/mtarsel/ICP-POWER-Up/master/install-icp-ppc64le.sh
        chmod +x install-icp-ppc64le.sh
        touch abc.txt
        echo "ICP MASTER IS ME!\n newline???" >> abc.txt
        ./install-icp-ppc64le.sh
